---
### PostgreSQL ###
postgresql_version: 10

postgresql_listen_addresses:
  - 'localhost'
postgresql_port: 5432

# NOTICE! For public servers write your `vaulted_*` variables in `vault.yml` and ecrypt it!
postgresql_databases:
  - name: '{{ vaulted_database_name }}'

postgresql_users:
  - name: '{{ vaulted_database_user }}'
    pass: '{{ vaulted_database_password }}'
    encrypted: yes

postgresql_user_privileges:
  - name: '{{ vaulted_database_user }}'
    db: '{{ vaulted_database_name }}'
    priv: 'ALL'
    role_attr_flags: "CREATEDB"