---
### Deploy ###
deploy_project_name: 'webapp'
deploy_env: develop
deploy_user: '{{ ansible_user }}'           # Set deploy user
deploy_group: '{{ deploy_user }}'               # Set deploy group

deploy_prefix: '/home/{{ deploy_user }}'
deploy_dir: '{{ deploy_prefix }}/{{ deploy_project_name }}' # Main directory for deploiment
deploy_etc_dir: '{{ deploy_dir }}/etc'          # Directory where placed configuration files
deploy_log_dir: '{{ deploy_dir }}/log'          # Directory where placed logs
deploy_run_dir: '{{ deploy_dir }}/run'          # Directory where placed unix sockets and pid files
deploy_src_dir: '{{ deploy_dir }}/src'          # Source's directory
deploy_bin_dir: '{{ deploy_dir }}/bin'          # Directory where placed scripts
deploy_dir_skip: []
csv_files_root: 'sales_data/csv/files'

### Domains ###
site_domain: 'webapp.local'
api_domain: 'api.{{ site_domain }}'
flower_domain: 'flower.{{ site_domain }}'

site_protocol: http

run_backend: yes
run_frontend: yes

### Options ###
skip_checkout: no
force_upgrade: no

### Firewall ###
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
